# Read the Docs Configuration File (Optional for Private Repository)
# See: https://docs.readthedocs.io/en/stable/config-file/v2.html
# 
# NOTE: This configuration is provided for potential future use with Read the Docs for Business.
# Currently, documentation is deployed via GitHub Pages (see .github/workflows/docs.yml)
# since this is a private repository and GitHub Pages works seamlessly with private repos.

version: 2

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

# Optionally build your docs in additional formats such as PDF and ePub
formats:
  - pdf
  - epub

# Optional but recommended, declare the Python requirements required
# to build your documentation
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
