name: Bug Report
description: Report a bug in the HOMEPOT Client
title: "[BUG]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug in the HOMEPOT Client. Please fill out this form to help us understand and resolve the issue.
        
        **Note**: This repository is private and restricted to HOMEPOT consortium members only.

  - type: checkboxes
    id: terms
    attributes:
      label: Consortium Member Verification
      description: Please confirm your authorization to access this repository
      options:
        - label: I am an authorized member of the HOMEPOT consortium
          required: true
        - label: I have proper authorization to report issues on behalf of my organization
          required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened
      placeholder: What actually happened?
    validations:
      required: true

  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Ubuntu 20.04
        - Ubuntu 22.04
        - Windows 10
        - Windows 11
        - macOS 12 (Monterey)
        - macOS 13 (Ventura)
        - macOS 14 (Sonoma)
        - Other (specify in additional context)
    validations:
      required: true

  - type: input
    id: client-version
    attributes:
      label: HOMEPOT Client Version
      description: What version of the HOMEPOT Client are you using?
      placeholder: e.g., 1.2.3
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Bug Severity
      description: How severe is this bug?
      options:
        - Critical - System unusable
        - High - Major functionality impacted
        - Medium - Some functionality impacted
        - Low - Minor issue
    validations:
      required: true

  - type: checkboxes
    id: use-cases
    attributes:
      label: Affected Use Cases
      description: Which HOMEPOT use cases are affected by this bug?
      options:
        - label: Retail operations
        - label: Hospitality management
        - label: Industrial control systems
        - label: Device management
        - label: Security and compliance
        - label: Cross-platform communication

  - type: textarea
    id: device-info
    attributes:
      label: Device/Endpoint Information (if applicable)
      description: Information about the device or endpoint involved
      placeholder: |
        - Device Type: [e.g., IoT sensor, POS terminal]
        - Device Model: [manufacturer and model]
        - Firmware Version: [e.g., 2.1.4]
        - Communication Protocol: [e.g., MQTT, HTTP]

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Please attach relevant log files or error messages
      render: shell

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here

  - type: input
    id: organization
    attributes:
      label: Partner Organization
      description: Your organization name within the consortium
      placeholder: e.g., University of XYZ, Company ABC
    validations:
      required: true

  - type: checkboxes
    id: security-check
    attributes:
      label: Security Considerations
      description: Security verification checklist
      options:
        - label: This bug report does not contain sensitive information
          required: true
        - label: This bug does not appear to be security-related (if it is, please use the security issue template instead)
          required: true
