"""Endpoints package for API v1."""

from . import (
    AgentHeartbeatEndpoint,
    AgentRegisterEndpoint,
    AgentsEndpoints,
    AgentStatusEndpoint,
    AgentTelemetryEndpoint,
    AIEndpoint,
    AnalyticsEndpoint,
    ClientEndpoint,
    DashboardEndpoint,
    DeviceCommandsEndpoint,
    DeviceCredentialEndpoint,
    DevicesEndpoints,
    DeviceSimulatorEndpoint,
    EnrolmentIntentsEndpoint,
    HealthEndpoint,
    JobsEndpoints,
    PushNotificationEndpoint,
    SiteSchedulesEndpoint,
    SitesEndpoint,
    TenantsEndpoint,
    UIEndpoint,
    UserRegisterEndpoint,
)

__all__ = [
    "AgentHeartbeatEndpoint",
    "AgentRegisterEndpoint",
    "AgentStatusEndpoint",
    "AgentTelemetryEndpoint",
    "AgentsEndpoints",
    "AIEndpoint",
    "AnalyticsEndpoint",
    "ClientEndpoint",
    "DashboardEndpoint",
    "DeviceCommandsEndpoint",
    "DeviceCredentialEndpoint",
    "DevicesEndpoints",
    "DeviceSimulatorEndpoint",
    "EnrolmentIntentsEndpoint",
    "HealthEndpoint",
    "JobsEndpoints",
    "PushNotificationEndpoint",
    "SiteSchedulesEndpoint",
    "SitesEndpoint",
    "TenantsEndpoint",
    "UIEndpoint",
    "UserRegisterEndpoint",
]
