#!/bin/bash
# HOMEPOT Client Environment Activation Script
# Generated by install.sh on Mon Sep  8 10:50:03 BST 2025

if [[ -f "venv/bin/activate" ]]; then
    source "venv/bin/activate"
    echo -e "\033[0;32mHOMEPOT Client environment activated\033[0m"
    echo "Virtual environment: venv"
    echo "Python: $(python --version)"
    echo ""
    echo "Available commands:"
    echo "  homepot-client version      # Show version"
    echo "  homepot-client info         # Show client info"
    echo "  homepot-client --help       # Show help"
    echo ""
    echo "To deactivate: deactivate"
else
    echo -e "\033[0;31mError: Virtual environment not found\033[0m"
    echo "Please run scripts/install.sh first"
    exit 1
fi
